[package]
name = "image_processor_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "image_processor_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module"] }
image = "0.24"
imageproc = "0.23"
rayon = "1.7" 